name: speak_sphere
description: "A new Flutter project."
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_animate: ^4.4.0
  google_fonts: ^6.1.0
  path_drawing: ^1.0.1
  gap: ^3.0.1
  animated_text_kit: ^4.2.2
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0


# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/
    - assets/images/icons/
    - assets/images/splash/
  uses-material-design: true

        
    
    
                                      